<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422073819 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // DROP messenger_messages — артефакт make:migration: Doctrine не видит
        // эту таблицу в коде (она managed Symfony Messenger), решает что её
        // надо удалить. На локалке таблица существовала (auto_setup в dev),
        // в проде на чистой БД её нет — без IF EXISTS падает с
        // «table "messenger_messages" does not exist». Следующая миграция
        // (Version20260427200000) её явно создаёт.
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');
        $this->addSql('ALTER TABLE tasks ADD respect_quiet_hours BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE tasks ADD single_reminder_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE tasks ADD single_reminder_sent_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE tasks ADD single_reminder_respect_quiet_hours BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE tasks DROP respect_quiet_hours');
        $this->addSql('ALTER TABLE tasks DROP single_reminder_at');
        $this->addSql('ALTER TABLE tasks DROP single_reminder_sent_at');
        $this->addSql('ALTER TABLE tasks DROP single_reminder_respect_quiet_hours');
    }
}
