<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Создаёт таблицу messenger_messages для Symfony Messenger doctrine-транспорта.
 *
 * Раньше создавалась автоматически в локалке через auto_setup. В проде нужна
 * явная миграция — иначе scheduler не сможет писать сообщения.
 *
 * Эта миграция идёт ПОСЛЕ Version20260422073819 (где DROP TABLE IF EXISTS),
 * поэтому в любом окружении (локалка где DROP отработал, прод где DROP no-op)
 * результат одинаковый: чистая, актуальная таблица.
 */
final class Version20260427200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages table for Symfony Messenger doctrine transport';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS messenger_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            body TEXT NOT NULL,
            headers TEXT NOT NULL,
            queue_name VARCHAR(190) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');
    }
}
